
//七型持续和结束后还原
IF
	Class(Player%PN%,PALADIN)
	OR(4)
		Kit(Player%PN%, c4JediA)
		Kit(Player%PN%, c4JediB)
		Kit(Player%PN%, c4JediC)
		Kit(Player%PN%, c4JediD)
	TriggerOverride(Player%PN%,Global("c4EF_Jedi_Style","Locals",%form%))
	!HasItemEquiped("c4efJj%form%",Player%PN%)
	TriggerOverride(Player%PN%,Global("c4EF_Jedi_Style_Form7","Locals",1))
	!GlobalTimerNotExpired("c4EF_Form7_Player%PN%","Global")
THEN
	RESPONSE #100
		ReallyForceSpellRES("c4efJj7%form%",Player%PN%)
		Continue()
END

